apiVersion: v1
kind: Pod
metadata:
  name: verify-unsigned
  namespace: ayoob-kyverno
  labels:
    app.kubernetes.io/name: demo
spec:
  containers:
  - name: test
    image: ghcr.io/kyverno/test-verify-image:unsigned
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi